name: Build CS2 External

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        msbuild catalyst/catalyst.vcxproj `
          -p:Configuration=Release `
          -p:Platform=x64 `
          -p:PlatformToolset=v143 `
          -p:WindowsTargetPlatformVersion=10.0 `
          -p:UseStaticLib=true `
          -p:WholeProgramOptimization=true `
          -m `
          -verbosity:minimal

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: catalyst
        path: bin/catalyst.exe
