name: Build CS2 External

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: 'C:/vcpkg'
        vcpkgGitCommitId: '501db0f17ef6df184fcdbfbe0f87cde2313b6ab1'
    
    - name: Install freetype
      run: C:/vcpkg/vcpkg install freetype:x64-windows-static
    
    - name: Build
      run: msbuild catalyst/catalyst.vcxproj -p:Configuration=Release -p:Platform=x64 -p:VcpkgEnabled=true -p:VcpkgTriplet=x64-windows-static -m
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: catalyst
        path: bin/catalyst.exe
